language: c
sudo: false

matrix:
  include:
    - env: GHCVER=7.10.1 CABALVER=1.22 JOPTS="-j2"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1,ghdl,gperf]
                    ,sources:  [hvr-ghc,pgavin-ghdl]}}
    - env: GHCVER=head CABALVER=head JOPTS="-j2"
      addons: {apt: {packages: [cabal-install-head,ghc-head,ghdl,gperf]
                    ,sources:  [hvr-ghc,pgavin-ghdl]}}

  allow_failures:
    - env: GHCVER=head CABALVER=head JOPTS="-j2"

cache:
  directories:
  - $HOME/iverilog
  - $HOME/.cabal-sandbox

before_cache:
  - rm -f $HOME/.cabal-sandbox/$GHCVER/packages/00-index.tar

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - export CABAL=cabal-$CABALVER
  - ghc --version
  - $CABAL --version
  - ghdl --version
  - |
    if [ -f $HOME/iverilog/bin/vvp ]; then
      echo 'Using cached iverilog.';
    else
      git clone -b v10-branch https://github.com/steveicarus/iverilog.git iverilog-source
      cd iverilog-source && sh autoconf.sh && ./configure --prefix=$HOME/iverilog && make && make install && cd ..
    fi
  - export PATH=$PATH:$HOME/iverilog/bin
  - vvp -V
  - travis_retry $CABAL update

install:
  - |
    if [ -f $HOME/.cabal-sandbox/$GHCVER/packages/00-index.tar ]; then
      rm -f $HOME/.cabal-sandbox/$GHCVER/packages/00-index.tar
    fi
  - $CABAL sandbox init --sandbox=$HOME/.cabal-sandbox/$GHCVER
  - $CABAL sandbox add-source testsuite
  - $CABAL install $JOPTS clash-testsuite
  - |
    if [ $GHCVER = "head" ]; then
      git clone https://github.com/clash-lang/ghc-tcplugins-extra.git
      git clone https://github.com/clash-lang/ghc-typelits-natnormalise.git
      $CABAL sandbox add-source ghc-tcplugins-extra
      $CABAL sandbox add-source ghc-typelits-natnormalise
    fi
  - git clone https://github.com/clash-lang/clash-prelude.git
  - $CABAL sandbox add-source clash-prelude
  - $CABAL sandbox add-source clash-lib
  - $CABAL install $JOPTS --dependencies-only clash-lib
  - $CABAL sandbox add-source clash-ghc
  - $CABAL sandbox add-source clash-systemverilog
  - $CABAL sandbox add-source clash-verilog
  - $CABAL sandbox add-source clash-vhdl

script:
  - $CABAL install $JOPTS clash-ghc
  - $CABAL exec clash-testsuite

notifications:
  irc:
    channels:
      - "irc.freenode.org#clash-lang"
    skip_join: true
    template:
      - "\x0313clash-compiler\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
