env:
  - GHCVER=7.8.4 CABALVER=1.22
  - GHCVER=7.10.1 CABALVER=1.22
  - GHCVER=head CABALVER=1.22

matrix:
  allow_failures:
    - env: GHCVER=head CABALVER=1.22

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - ghc --version
  - cabal --version

install:
  - travis_retry cabal update
  - cabal install --dependencies-only --enable-tests
  - cabal configure --enable-tests

script:
  - cabal build
  - cabal test --show-details=always

  # tests that a source-distribution can be generated
  - cabal sdist

  # check that the generated source-distribution can be built & installed
  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then
       cabal install --force-reinstalls "$SRC_TGZ";
    else
       echo "expected '$SRC_TGZ' not found";
       exit 1;
    fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#clash-lang"
    skip_join: true
    template:
      - "\x0313ghc-typelits-natnormalise\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
