env:
  - GHCVER=7.10.1 CABALVER=1.22
  - GHCVER=head CABALVER=1.22

matrix:
  allow_failures:
    - env: GHCVER=head CABALVER=1.22

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo add-apt-repository -y ppa:pgavin/ghdl
  - travis_retry sudo add-apt-repository -y ppa:team-electronics/ppa
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER ghdl verilog
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - ghc --version
  - cabal --version
  - ghdl --version
  - vvp -V

install:
  - git clone https://github.com/clash-lang/clash-prelude.git
  - git clone https://github.com/clash-lang/ghc-tcplugins-extra.git
  - git clone https://github.com/clash-lang/ghc-typelits-natnormalise.git
  - travis_retry cabal update
  - cabal sandbox init
  - cabal sandbox add-source ghc-tcplugins-extra
  - cabal sandbox add-source ghc-typelits-natnormalise
  - cabal sandbox add-source clash-prelude
  - cabal sandbox add-source clash-ghc
  - cabal sandbox add-source clash-lib
  - cabal sandbox add-source clash-systemverilog
  - cabal sandbox add-source clash-verilog
  - cabal sandbox add-source clash-vhdl
  - cabal sandbox add-source testsuite

script:
  - cabal install clash-ghc
  - cabal install clash-testsuite
  - cabal exec clash-testsuite

notifications:
  irc:
    channels:
      - "irc.freenode.org#clash-lang"
    skip_join: true
    template:
      - "\x0313clash-compiler\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
