version: 2

aliases:
  - &env
    TERM: xterm-color
    THREADS: 1
    CABAL_JOBS: 1

    RUN_HADDOCK: "yes"
    RUN_LIBTESTS: "yes"
    RUN_CLASHDEV: "yes"
    RUN_TESTSUITE: "yes"
    RUN_BUILD_ALL: "yes"

    MULTIPLE_HIDDEN: "yes"

    # Used to detect partial evaluator branches on Gitlab CI
    CI_COMMIT_BRANCH: "xxxx"
  - &submodules
    run:
      name: "Checkout submodules"
      command: git submodule update --init
  - &setup
    run:
      name: Setup system
      command: |
        # Only test on external pull requests
        if [ -n "$CIRCLE_PR_NUMBER" ]; then
          .ci/setup.sh
        fi
  - &cache_calc_key
    run:
      name: Calculate cache key
      command: |
        date +%Y-%m > /.circleci_cachekey
        if [ -e /usr/bin/gcc ]; then /usr/bin/gcc --version >> /.circleci_cachekey; fi
        cat /.circleci_cachekey
  - &cache_restore
    restore_cache:
      keys:
        - cache-{{ checksum "/.circleci_cachekey" }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
        - cache-{{ checksum "/.circleci_cachekey" }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-
        - cache-{{ checksum "/.circleci_cachekey" }}-{{ .Environment.CIRCLE_JOB }}-
  - &cache_save
    save_cache:
      key: cache-{{ checksum "/.circleci_cachekey" }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
      paths:
        # Don't hit Ubuntu servers for same packages over and over
        - /var/cache/apt/
        # Don't hit cache.nixos.org for same packages over and over
        - /nix
        # Cache Clash dependencies
        - cabal-store
        # Cache dependencies and ghc binaries
        - ~/.stack

  - &build
    run:
      name: Build dependencies and Clash itself
      command: |
        # Only test on external pull requests
        if [ -n "$CIRCLE_PR_NUMBER" ]; then
          .ci/build.sh
        fi

  - &nix_setup
    run:
      name: Setup binaries (such as git)
      command: |
        # Circle CI needs git/ssh in /usr/bin
        nix-env -i git findutils gnugrep gnused coreutils openssh bash-4.4-p23

        #                               bin         nix pkg        multiple may exist
        ln -s $(find /nix -type f -name git  | grep libexec      | head -n1) /usr/bin
        ln -s $(find /nix -type f -name ssh  | grep openssh      | head -n1) /usr/bin
        ln -s $(find /nix -type f -name sed  | grep gnused       | head -n1) /usr/bin
        ln -s $(find /nix -type f -name bash | grep bash-4.4-p23 | head -n1) /bin

  - &nix_build
    run:
      name: Build dependencies and Clash itself with Nix
      command: .ci/nix_build.sh
      no_output_timeout: 1h

  - &stack_build
    run:
      name: Build dependencies and Clash itself with Stack
      command: .ci/stack_build.sh

  - &run_tests
    run:
      name: Run tests
      command: |
        # Only test on external pull requests
        if [ -n "$CIRCLE_PR_NUMBER" ]; then
          cabal v2-test clash-prelude
          cabal v2-test clash-lib
          cabal v2-test clash-cores
          cabal v2-test clash-cosim
          cabal v2-run testsuite -- --hide-successes -p .VHDL
          cabal v2-run testsuite -- --hide-successes -p .Verilog
        fi
      no_output_timeout: 1h

  # When testing a pull request on CircleCI,
  # fetch the result of merging it in.
  - &merge_pullrequest
    run:
      name: Checkout pull request merge result
      command: |
        if [ -n "$CIRCLE_PR_NUMBER" ]; then
          git fetch "$CIRCLE_REPOSITORY_URL" "pull/$CIRCLE_PR_NUMBER/merge:pull-$CIRCLE_PR_NUMBER-merged"
          git rev-parse "pull-$CIRCLE_PR_NUMBER-merged"
          git checkout "pull-$CIRCLE_PR_NUMBER-merged"
        fi

  - &build_default
    docker:
      - image: docker.pkg.github.com/clash-lang/clash-compiler/clash-ci:2020-11-20
        # Read-only permissions
        auth:
          username: clash-lang-builder
          password: $DOCKER_PASS
    steps:
      - checkout
      - *merge_pullrequest
      - *submodules
      - *setup
      - *cache_calc_key
      - *cache_restore
      - *build
      - *cache_save
      - *run_tests
  - &build_with_stack
    docker:
      - image: docker.pkg.github.com/clash-lang/clash-compiler/clash-ci:2020-11-20
        # Read-only permissions
        auth:
          username: clash-lang-builder
          password: $DOCKER_PASS
    steps:
      - checkout
      - *merge_pullrequest
      - *submodules
      - *cache_calc_key
      - *cache_restore
      - *stack_build
      - *cache_save
  - &build_with_nix
    docker:
      - image: nixos/nix
    steps:
      - *cache_calc_key
      - *cache_restore
      - *nix_setup
      - checkout
      - *merge_pullrequest
      - *submodules
      - *nix_build
      - *cache_save

workflows:
  version: 2
  build_and_test_clash:
    jobs:
      - ghc-8.4.4
      - ghc-8.6.5-singular-hidden
      # - ghc-8.6.5
      - ghc-8.8.4
      - ghc-8.10.2
      - stack-build
      - nix-build

jobs:
  ghc-8.4.4:
    environment:
      <<: *env
      GHC_VERSION: 8.4.4
    <<: *build_default
  ghc-8.6.5:
    environment:
      <<: *env
      GHC_VERSION: 8.6.5
    <<: *build_default
  ghc-8.8.4:
    environment:
      <<: *env
      GHC_VERSION: 8.8.4
    <<: *build_default
  ghc-8.10.2:
    environment:
      <<: *env
      GHC_VERSION: 8.10.2
    <<: *build_default
  ghc-8.6.5-singular-hidden:
    environment:
      <<: *env
      GHC_VERSION: 8.6.5
      MULTIPLE_HIDDEN: no
    <<: *build_default
  stack-build:
    environment:
      <<: *env
    <<: *build_with_stack
  nix-build:
    environment:
      <<: *env
    <<: *build_with_nix
